### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by bruinxs** [anacrolix/missinggo#13]
when I `go get -v github.com/anacrolix/missinggo`，error happen:

```
github.com/anacrolix/missinggo
# github.com/anacrolix/missinggo
../../go/src/github.com/anacrolix/missinggo/section_read_seeker.go:25: cannot use sectionReadSeeker literal (type *sectionReadSeeker) as type ReadSeekContexter in assignment:
        *sectionReadSeeker does not implement ReadSeekContexter (wrong type for ReadContext method)
                have ReadContext("context".Context, []byte) (int, error)
                want ReadContext("golang.org/x/net/context".Context, []byte) (int, error)
```

if forgot to fix reader_context.go file import context package?

**Comment by bruinxs** [comment]
the resume is go version, it's resolved after I update golang to 1.9

**Comment by anacrolix** [comment]
Thanks for catching that. I've updated the context imports through the repo. https://github.com/anacrolix/missinggo/commit/121b43209037cbdc044dd1e4ced064a8c4ab2894
